In [5]:
import numpy as np

a = np.array([0.3, 2.9, 4.0])
exp_a = np.exp(a)   # 지수 함수
print(exp_a)

sum_exp_a = np.sum(exp_a)   # 지수 함수의 합
print(sum_exp_a)

y = exp_a /sum_exp_a
print(y)

[ 1.34985881 18.17414537 54.59815003]
74.1221542101633
[0.01821127 0.24519181 0.73659691]


In [12]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y
# 오버플로우 발생 가능성

1.0

In [17]:
a = np.array([1010, 1000, 990])
np.exp(a) / np.sum(np.exp(a))   # 소프트맥스 함수의 계산
# array([nan, nan, nan])    # 오버플로우로 계산이 되지 않음.

c = np.max(a)   # a의 최대값 즉 c = 1010(최대값)
print(a - c)    # 오버플로우를 막기 위해서 최대값을 빼줌.

np.exp(a - c) / np.sum(np.exp(a - c))   # 그 후 소프트맥스 구현

[  0 -10 -20]


C:\Users\vlrms\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  
C:\Users\vlrms\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [49]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c) #오버플로우 방지
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

input_num = np.array([0.3, 2.9, 4.0])
output_num = softmax(input_num)
np.round(output_num, 5) # 5번째 자리에서 반올림


array([0.01821, 0.24519, 0.7366 ])